### ISSUE TITLE
Mejorar aspectos visuales

### ISSUE THREAD

**Issue by valenshinga** [valenshinga/xvdreams#13]
ACLARACION: USAR JQUERY PARA MANEJO DE DOMINIO Y ULTIMA VERSION DE BOOTSTRAP PARA ASPECTOS. SI usan GPT revisen la version de bootstrap que les pone, porque es vieja y rompe todo. Si no lo corrijen, yo no lo voy a hacer y no lo voy a mergear hasta que quede resuelto

**Comment by valenshinga** [comment]
ACLARACION: USAR JQUERY PARA MANEJO DE DOMINIO Y ULTIMA VERSION DE BOOTSTRAP PARA ASPECTOS

**Comment by ruohl** [comment]
OK 🗣️🗣️🗣️🔥🔥🔥

**Comment by valenshinga** [comment]
Dejarlo en espera hasta terminar https://github.com/valenshinga/xvdreams/issues/16
