### ISSUE TITLE
ANUNCIOOOOOO!! LEER SI O SI!!

### ISSUE THREAD

**Issue by valenshinga** [valenshinga/xvdreams#41]
Desde ahora, todas las tareas asignadas, tienen un plazo maximo de 1 semana para terminarse desde que se asignaron (las de ahora tienen hasta el martes). A como venimos de ritmo ahora, dudo mucho que lleguemos bien con el proyecto, y yo no voy a estar a las corridas orquestando todo. Ponganse las pilas y terminen lo que tengan a tiempo. Saquemonos esto de encima

**Comment by JV4MP1** [comment]
**Funcionalidad > detalle** 
pd: Diegovich
