### ISSUE TITLE
Sign in para proveedores

### ISSUE THREAD

**Issue by valenshinga** [valenshinga/xvdreams#59]
hacer la pagina de registro para proveedores

**Comment by valenshinga** [comment]
SOLO HACER EL REGISTRO. EL LOGIN NO ES NECESARIO

**Comment by ruohl** [comment]
![Diagrama sin título drawio](https://github.com/user-attachments/assets/c66f9129-7fb5-4d03-b3c7-9f0ccd0f3b78)

**Comment by valenshinga** [comment]
Hacer q el registro, genere documentos en la DB que esten adentro de la coleccion de "Users". Estos documentos tienen que tener como datos los que estan en la imagen de arriba q correspondan a los proveedores

**Comment by valenshinga** [comment]
No hagas cagada con la DB. Asegurate de que envias bien los datos. Sino despues eliminar todo eso es un dolor de cabeza
